service: serverless-test-func
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
functions:
  test-func:
    handler: handler.main
    events:
      - http:
          path: /
          method: get